export const routePaths = {
  home: '/',
  login: '/login',
  register: '/register',
  sellerRegister: '/seller-register',
  books: '/books',
  cart: '/cart',
  orders: '/orders',
  customerProfile: '/customer/profile',
  sellerDashboard: '/seller/dashboard',
  sellerListings: '/seller/listings',
  sellerOrders: '/seller/orders',
  sellerProfile: '/seller/profile',
  adminDashboard: '/admin/dashboard',
  adminProfile: '/admin/profile',
}
